### ISSUE TITLE
Setup SE SDK framework

### ISSUE THREAD

**Issue by UnknownmAc** [blunderboy/stackexchange-sdk#3]
## Tasks:

- [ ] What should be Project Structure ?
- [ ] Initial API to start with ?
- [ ] Where to put documentation ?

**Comment by blunderboy** [comment]
@UnknownmAc I am listing various options we have for documentation:

## Gitbook
  - Example: http://www.frontendhandbook.com/

## Swagger

### Pros
- Pretty famous. Need to figure out why :) 

## ReadMe.io (http://readme.io/)

### Pros:
  - Multiple Layouts available
